

name: CI


on:
  workflow_call:
    inputs:
      working-directory:
        description: "Working-directory what dir to scan"
        required: false
        default: .
        type: string
    secrets:
      EE_CHECKOUT_TOKEN:
        required: true
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      EE_CHECKOUT_TOKEN: ${{ secrets.EE_CHECKOUT_TOKEN }}
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: branch message
        shell: bash
        run: |
          env
          echo "Current branch: $(git branch --show-current)"
